### ISSUE TITLE
Метод строкового представления

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/ExampleCircle#2]
Метод строкого представления у вас подразумевает, будто пользователь что-то делал с предметом. Представьте, что вы рисуете круг на доске и говорите (чтобы его описать), что у него "обновленные координаты какие-то". То есть, когда пользователь создаёт круг и перемещает его в другую точку, ему будет странно получить слова об якобы обновленном радиусе.

**Comment by escos** [comment]
Не совсем понимаю тогда, что именно требуется в этом методе или у меня в содержании выводимой информации не то, а именно в сообщении??

**Comment by anastasiya-solodkaya** [comment]
Я скорее про сообщение. У вас метод возвращает строковое представление ОБЪЕКТА, а реально печатается строковое описание изменений (которые не факт, что были сделаны). Речь о сообщении, да

**Comment by escos** [comment]
Сообщение исправил.
