### ISSUE TITLE
Сравнение чисел типа double

### ISSUE THREAD

**Issue by anastasiya-solodkaya** [escos/ExampleCircle#5]
На самом деле числа типа double сравнивают с учётом некоторой погрешности. Попробуйте сравнить результат 10.0 + 1.0 и 10.0 + (10 раз в цикле по 0.1).
Можно ещё посмотреть на число 0.2 в double (выведитп на экран) и возвести в степень числа 10.2, 1000.2 и 1000000.2 и посмотреть на получившуюся погрешность. :) это не только с операциями связано, но и с тем, что некоторые числа не представимы в числе двойной точности. 

Поэтому могут подобраться данные, когда ваше сравнение < radius, > и = просто не сработают из-за накопленной погрешности. Поэтому обычно берётся некое епсилон и значения сравниваются с определённой точностью

**Comment by escos** [comment]
Добавил точность в 0,001.

**Comment by anastasiya-solodkaya** [comment]
Вроде стандартно берут 10^-6, потому что 10^-3 - это довольно-таки мало. Но это ок, я думаю.
